### ISSUE TITLE
When MetalLB is enabled, BGP messes up the controlplane node

### ISSUE THREAD

**Issue by clrxbl** [equinix/cloud-provider-equinix-metal#174]
@deitch

**Comment by deitch** [comment]
Thanks for opening this @clrxbl 

The heart of the issue is that metallb tries to manage the controlplane service created by CPEM. Even though CPEM annotates the service with `metallb.universe.tf/address-pool: disabled-metallb-do-not-use-any-address-pool`, that only prevents metallb from _assigning_ the address, not from _announcing_ it. That announcement conflicts with the EM API assignment, and things start going to strange places.

The solution is to ensure that the special service is annotated additionally, and then ensure we never pass it to the metallb implementation.
