### ISSUE TITLE
Switch LoadBalancer Elastic IP requests from Facility to Metro

### ISSUE THREAD

**Issue by enkelprifti98** [equinix/cloud-provider-equinix-metal#181]
With the rollout of Metros in Equinix Metal, the CCM should make "Metro" Elastic IP requests instead of the facility IP requests:

https://github.com/equinix/cloud-provider-equinix-metal/blob/master/metal/loadbalancers.go#L367

**Comment by deitch** [comment]
It does now. It reads the config/env-var/CLI flags for metro or facility, and takes whichever one the user asked for. See [here](https://github.com/equinix/cloud-provider-equinix-metal#equinix-eip)

Going to close this out, but if it needs reopening because I misunderstood, feel free. If it is a different but related issue, please open a new one.
