### ISSUE TITLE
Update documentation for 1.23

### ISSUE THREAD

**Issue by displague** [equinix/cloud-provider-equinix-metal#188]
Kubernetes 1.22 deprecates the --cloud-provider kubelet argument, with its removal set for 1.23.

What does this mean for CPEM? Presumably, some documentation will need to reflect changes if nothing else.

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

>  The provider for cloud services. Set to empty string for running with no cloud provider. If set, the cloud provider determines the name of the node (consult cloud provider documentation to determine if and how the hostname is used). (DEPRECATED: will be removed in 1.23, in favor of removing cloud provider code from Kubelet.)

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#feature-3

> Introduce a feature gate DisableCloudProviders allowing to disable cloud-provider initialization in KAPI, KCM and kubelet.

DisableCloudProviders FeatureGate is currently in Alpha, which means is currently disabled by default. Once the FeatureGate moves to beta, in-tree cloud providers would be disabled by default, and a user won't be able to specify --cloud-provider=<aws|openstack|azure|gcp|vsphere> anymore to any of KCM, KAPI or kubelet. Only a --cloud-provider=external would be allowed. CCM would have to run out-of-tree with CSI. (#100136, @Danil-Grigorev) [SIG API Machinery, Cloud Provider, Instrumentation and Node]

**Comment by deitch** [comment]
This confused me. If `--cloud-provider` is deprecated, then how can you run it with `--cloud-provider=external`?

**Comment by detiber** [comment]
The verbiage in the changelog is definitely confusing, based on reading the related KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers and the PR adding the new DisableCloudProviders FeatureGate: https://github.com/kubernetes/kubernetes/pull/100136/files, this will not impact --cloud-provider=external, which appears to still be needed for use with external cloud provider implementations...

The deprecation notice on the kubelet --cloud-provider flag seems odd, since it seems like it'll still be needed 🤷🏻

**Comment by displague** [comment]
Further discussion on `--cloud-provider` deprecation:
https://github.com/kubernetes/kubernetes/issues/110018
