### ISSUE TITLE
enable ToR switch routes via "Route" controller

### ISSUE THREAD

**Issue by displague** [equinix/cloud-provider-equinix-metal#190]
The Route controller <https://kubernetes.io/docs/concepts/architecture/cloud-controller/#route-controller> feature of the cloud provider should add the following routes under the condition that the Facility has the "ibx" flag.

When this ToR route is not present, MetalLB or KubeVIP will not be able to configure BGP. https://github.com/equinix/cloud-provider-equinix-metal/blob/master/README.md#bgp

Effectively:
```
GATEWAY_IP=$(curl https://metadata.platformequinix.com/metadata | jq -r ".network.addresses[] | select(.public == false) | .gateway")
ip route add 169.254.255.1 via $GATEWAY_IP
ip route add 169.254.255.2 via $GATEWAY_IP
```

CPEM sets the metal.equinix.com/peer-ips annotation, which suggests that CPEM has some responsibility to ensure that the peer ips presented to pods is correct and actionable.  CPEM already activates BGP (via the EM API) on devices that do not have it enabled, perhaps this should be a function of the route controller.

Arguably, these routes should be persisted, but it should be sufficient for CPEM to activate the routes when they are missing and required.

---

_I'm open to debate on where the responsibility of setting these routes should be. This issue takes the position that it should be in the CPEM and we can debate or accept that premise here._

**Comment by deitch** [comment]
it cannot. The Route controller, as described above, is presumed to do all of that in coordination with the cloud provider API. In the case of the routes above, these aren't _cloud provider_ routes but _on device_ routes. CPEM runs in a single place, not on every node.

> CPEM sets the metal.equinix.com/peer-ips annotation, which suggests that CPEM has some responsibility to ensure that the peer ips presented to pods is correct and actionable

True, but it also sets `metal.equinix.com/src-ip` annotation, so that software can use that as the source when making a network connection.

kube-vip supports the above, reads the annotation and then sets the source IP for the peering packets to the correct IP, so it actually does not need the `ip route add` command in order to work; the annotations are enough.

metallb is a whole different beast. It is one of the only pieces of network software I have seen that doesn't have the ability to set the source IP when opening a socket. There has been a _very_ longstanding request for it, as well as an open PR for annotations (1 year? 2 years? not sure). This is one of (several) reasons we recommend people use kube-vip if possible.

> I'm open to debate on where the responsibility of setting these routes should be. This issue takes the position that it should be in the CPEM and we can debate or accept that premise here.

Understood. I think CPEM _could_ take that responsibility if one of two things were true:

* CPEM already ran as a DaemonSet - it doesn't, none does, and it adds a lot of complexity
* CPEM could somehow direct (or trick) Kubernetes into creating these (like we do for the EIP routes) - it cannot

Given that kube-vip supports setting source route (as does bird and just about every other piece of bgp, or even general networking, software), and it would add a lot of overhead to try and add it to CPEM, I would shy away.

My $0.03 (inflation is really increasing).

**Comment by displague** [comment]
> kube-vip supports the above, reads the annotation and then sets the source IP for the peering packets to the correct IP, so it actually does not need the ip route add command in order to work; the annotations are enough.

In a recent demo, @thebsdbox and I needed to manually add the `169.254.255.1` and `2` routes for kube-vip.

> CPEM already ran as a DaemonSet - it doesn't, none does, and it adds a lot of complexity

(we chatted about this part elsewhere, but I'll repeat here)

I took a look at https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_routes.go to see what they were doing. The size of this CCM is daunting.

They include the recommendation: ’It is recommended to run azure-cloud-controller-manager as Pods on master nodes.’ which suggests that the CCM pod does not run on worker nodes.  The Azure CCM manifests includes a DaemonSet called `cloud-node-manager` which I suspect may be how they execute local route modifications.  I don't know how the node-manager receives its instructions. In our case, it could be done through annotations.

> True, but it also sets metal.equinix.com/src-ip annotation, so that software can use that as the source when making a network connection.

I think this point is lost on me. Is this to suggest that `kube-vip` should be taking advantage of this annotation to avoid the need for the static routes? Is this an feature kube-vip has today?

**Comment by deitch** [comment]
> I think this point is lost on me. Is this to suggest that kube-vip should be taking advantage of this annotation to avoid the need for static routes? Is this a feature kube-vip has today?

I believe it is. @thebsdbox ?

**Comment by flokli** [comment]
> (we chatted about this part elsewhere, but I'll repeat here)

That happened in https://github.com/equinix/cloud-provider-equinix-metal/issues/183.

**Comment by flokli** [comment]
> metallb is a whole different beast. It is one of the only pieces of network software I have seen that doesn't have the ability to set the source IP when opening a socket. There has been a _very_ longstanding request for it, as well as an open PR for annotations (1 year? 2 years? not sure). This is one of (several) reasons we recommend people use kube-vip if possible.

MetalLB recently received support for it: https://github.com/metallb/metallb/pull/902. It's not yet in a stable release, though - but I poked in the PR just now.

**Comment by deitch** [comment]
I do not believe it, it actually came in. We probably should update the CCM to support it.

**Comment by deitch** [comment]
Actually, we did, with release v3.4.0, which sets the right things for metallb. We can close this now.
