### ISSUE TITLE
Support node name != hostname

### ISSUE THREAD

**Issue by flokli** [equinix/cloud-provider-equinix-metal#194]
When a new node appears in the cluster, https://github.com/equinix/cloud-provider-equinix-metal/blob/7e3189de8abd08dcae35cf052b45326c29f79b7b/metal/devices.go#L212 right now (only) does a match of the hostname, and checks if it finds something in Equinix Metal, then maps it to that node.

Node names are not necessarily equal to the hostname configured in Equinix Metal.

For example, I want to use k3s with the [`--with-node-id` parameter](https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#node), which appends a (random) id to the node name on registration. This causes the node to be not recognized by Equinix Metal CCM at all.

Instead of doing a simple hostname match, it should probably look at some of the data the node reports on itself (external IP maybe?) to do the matching.

**Comment by thebsdbox** [comment]
What errors are created by the CCM? Just wondering if it's something similar to #193 ?

**Comment by flokli** [comment]
Reading through the code, it simply returns `cloudprovider.InstanceNotFound`, and doesn't consider it an EQXM node - which causes other problems further down the line, of course.

**Comment by deitch** [comment]
It is called in 4 places, all of which are part of the cloud provider API, passing it the node name, and expecting it to find information about the node, where the node name should be sufficient to find it.

Are you proposing that the node name still is sufficient to find the unique cloud provider device, but instead of a name-to-hostname match, it uses the node name to get the node object from k8s, then uses info on the k8s node object to discover the actual device?

I am not 100% certain that the node is a full k8s object when some of these are called, although AWS's cloud provider [here](https://github.com/kubernetes/cloud-provider-aws/blob/eb0af203d93d28efea721d38ca897b3ac91c4484/pkg/providers/v1/aws.go#L5105-L5123) does just what you suggested, while GCP [here](https://github.com/kubernetes/cloud-provider-gcp/blob/39b722acff2538494294ab5e5ebd029836b00451/providers/gce/gce_instances.go#L656-L674) does make the node name = cloud provider name.

The above does assume that provider ID is populated correctly in the first place, which I cannot recall. If it depends on nodename-to-provider-ID, then we will have a catch-22. If the providerID is populated independently of the name (how?) then it could work.

I am hoping @detiber or @displague might know how the initial provider ID is populated, which call in the cloud provider gets it?

**Comment by flokli** [comment]
In my case, I invoke the k3s installation setting `INSTALL_K3S_EXEC="--node-ip $private_ipv4 --node-external-ip $public_ipv4 --with-node-id"` - these values come from a call to the metadata server.

If these two ips are already present in the `Node` object when the EQXM CCM gets to see it, yes, looking up the Node object by the name passed in, and in case there's not a clear hostname match, trying to match on the IPs should work.

Personally, I'd even think a matching nodes' external ip is a way stronger marker than just a matching hostname ;-)

**Comment by deitch** [comment]
> Personally, I'd even think a matching nodes' external ip is a way stronger marker than just a matching hostname ;-)

I wouldn't disagree. But the cloud provider interface in lots of places does "by node name", which seems to assume that node names match. Then again, as I linked to above, that isn't true across all providers; some assume node name match, others use it to get the k8s node object, and then use the provider ID in there to get the node.

If we can be confident that provider-ID is populated correctly, I am comfortable changing this to use the above-described algorithm: node name -> node object -> provider ID -> EQXM device. Awaiting @detiber or @displague commenting.

**Comment by deitch** [comment]
Digging a little deeper, when the AWS cloud-provider tries to look up the instance ID by node name, if it fails (e.g. it doesn't have providerID set yet), it actually calls [this](https://github.com/kubernetes/cloud-provider-aws/blob/eb0af203d93d28efea721d38ca897b3ac91c4484/pkg/providers/v1/aws.go#L5044-L5064) function, which treats the node name as the private DNS name rather than the hostname.

Either way, as far as I can tell, k8s cloud provider throughout requires that there has to be some inherent mapping between k8s node name and cloud-provider name. That is the lowest level of mapping.

**Comment by deitch** [comment]
btw, @flokli what is your Kubernetes workspace Slack ID?

**Comment by flokli** [comment]
I'm flokli in eqix-metal-community.slack.com ;-)

**Comment by detiber** [comment]
Node name limitations based on the cloud-provider interface seems to be the gift that just keeps on giving 😂.

I'm a huge +1 on removing any matching based on name wherever possible, however as @deitch has already mentioned, it'll be difficult to do in the case where the providerID has not yet been populated (since we are responsible for populating it) and there is some baked in expectations to the cloud provider interface that the node name will match some attribute within the cloud provider's api.
- For AWS, this is the private dns name as @deitch mentioned
- For OpenStack, it's the instance "name"
- And we've used the "hostname" attribute

Unfortunately, I think this is one place where the out-of-tree cloud providers are at a disadvantage. In the old/in-tree model, the kubelet could interrogate the cloud provider API and choose a different node name and set the providerID prior to creating it's own Node resource. In that model, we'd be able to query the metadata service or leverage local cloud-init provided data to "do the right thing".

In the out-of-tree model, the kubelet creates the Node resource prior to the "cloud provider" being involved, falling back to local Node naming semantics by default (I believe it first attempts to use a DNS lookup of the IP associated with the default route, falling back to a simple hostname lookup) and applying a taint to the Node. It is then up to the out-of-tree cloud-provider implementation to set the providerID (and any other additional info), and remove the taint.

I haven't been following much of the upstream discourse around the migration of in-tree providers to out-of-tree, but I suspect that this is also going to be a frustration that is faced by the other providers as their out-of-tree implementations are adopted as well.

**Comment by deitch** [comment]
So however you play it, node name is the linchpin around which the cloud provider is expected to identify the node. It would be great if there were a way to override that - e.g. if, when launching kubelet, I could tell it, "here is the provider ID you should use", or at least some identifier that would get passed to the CCM - but I don't think that exists?

I sort of thought `--hostname-override` might do it, but then we are forcing the user to use the cloud provider (EQXM) designated hostname instead of their desired one, which brought us here in the first place.

@flokli is there any reason why you cannot do both?

* when creating the EQXM device, set the desired hostname
* when launching the kubelet, pass it `--hostname-override=<that desired hostname>`

I don't think the above would work with the k3s `--with-node-id` option, as you do not _know_ the nodename until it runs.

In the end, there has to be some common identifier between the cloud provider device and the k8s node.

**Comment by detiber** [comment]
So, it is possible to specify the provider-id directly to the kubelet (through the --provider-id command line argument). We actually do this in the tinkerbell provider for cluster-api (https://github.com/tinkerbell/cluster-api-provider-tink) to work around the lack of cloud-provider implementation that we currently have.

I'm not sure how setting that field would impact deployments where cloud-provider=remote is configured, though.

**Comment by flokli** [comment]
@deitch I still think there should be a distinction between a nodes *network* hostname (provided by EQXM), and how that node registers itself to k8s - The CCM not being able to find nodes that have a different k8s *node name* is what this bug is about.

The `k3s` `--with-node-id` is one way to ensure nodes have unique names. Without it, there's all kinds of issues of new nodes suddenly "coming back" with an old, previously used node name. Think of (local) persistent volumes still with `nodeAffinity` to that  node name, but which never were created on that box, rook-ceph crush map node entries, …

@detiber so, to make sure I understand that correctly, I could manually set the provider id, by passing the `--provider-id` to kubelet, with a value like `equinixmetal://$uuid-from-metadata-server`?
How would the rest of the CCM behave? Would all the labelling still work? Or are there more calls to the API looking up a node with it's node name as hostname (what you referred to with "I'm a huge +1 on removing any matching based on name wherever possible")?

I could imagine setting the provider id manually, and only using the CCM to provide the rest of the information, assuming it would work that way.

Stretching this a bit further…

Let's say we removed all name-based lookups (to use the provider id when populated), except when initially determining the provider id - which facts does the "fresh" `Node` resource already have populated that could help us find a corresponding EQXM instance, (as a fallback, if there's no strict hostname match)?

On a cluster without the CCM deployed, I see the `status.addresses` list filled (unfortunately only the private IP). Maybe we could do a prefix match, in case the private IP matches.
If we are a bit creative and not too late for that, some CNIs also label nodes with public addresses before the `node.cloudprovider.kubernetes.io/uninitialized` taint is removed (like `flannel.alpha.coreos.com/public-ip` for example)

**Comment by deitch** [comment]
I'm moderately fine with having a distinct k8s node name from EQXM (and network) hostname. As above, no one else does it - aws is closest, but it just use the private FQDN instead of just the hostname - but everyone else is using the hostname or some variant.

We cannot get rid of the lookups by node name; the entire cloud-provider api to ccm is built around it. We _can_ use that to get some info from k8s, and then use that info to get the device, as you suggested. 

My concerns are:

- How do we initially get it populated? We need a process that works for everyone (default case), without burdening them to have to lookup and set the provider id on startup. The most common use case must work. 
- How do we link it? Using `--provider-id` works, but is less than optimal. Even the slightest error would break things. I would sooner see us do something like setting a tag on the EQXM device, or something else, but that would have the same issue you described above. Perhaps an annotation on the node? We can do that on kubelet startup, can we not @detiber ? Or is just using `--provider-id`, and telling users, "you break it, you own it", better?

Either way, whatever we do for the second issue must work with the first.

**Comment by flokli** [comment]
> How do we initially get it populated? We need a process that works for everyone (default case), without burdening them to have to lookup and set the provider id on startup. The most common use case must work.
>
> How do we link it? […]

The way I understand this is that the provider id is allocated once, either provided by the node (via `--provider-id` arg), or done by the EQXM CCM (if the provider id isn't already set).

We can keep the `node name == hostname` assumption when doing that lookup.

Maybe be a bit more forgiving, and also bind if there's some prefix match with a machine in EQXM whose ip address also matches.

But the rest of the code implementing the cloud-provider api (everything except the lookup) should always look at the `Node` object, and the provider id in there - not treat the Node object as a hostname.

**Comment by deitch** [comment]
> The way I understand this is that the provider id is allocated once, either provided by the node (via --provider-id arg), or done by the EQXM CCM (if the provider id isn't already set).

Correct.

> We can keep the node name == hostname assumption when doing that lookup.

I would like to get more power out of this, and @detiber started an interesting conversation with the maintainers on Slack, but that is a ways off. So for now, it has to stay that way.

> But the rest of the code implementing the cloud-provider api (everything except the lookup) should always look at the Node object, and the provider id in there - not treat the Node object as a hostname

What does it buy us? If the match of node name and host name was true when provider ID was set, it will stay the same. What do we gain?

**Comment by flokli** [comment]
> > But the rest of the code implementing the cloud-provider api (everything except the lookup) should always look at the Node object, and the provider id in there - not treat the Node object as a hostname

> What does it buy us? If the match of node name and host name was true when provider ID was set, it will stay the same. What do we gain?

Because the match could not have been true when the `ProviderID` was set via `--provider-id`.
Then the rest just breaks, cause it can't find the node name as an equinix metal hostname.

**Comment by deitch** [comment]
Oh, I think that makes sense. It narrows the area of question.

OK, let's go for this.

**Comment by grebennikov** [comment]
@deitch The original issue with Juju has been resolved. I'm able to have the kubelets to run with the IP addresses registered at the Metal side, so the controller can match them and the Equinix nodes.
The root cause was related to the fact that the internal subnets are being exposed through the API of Equinix are 10.X.X.X/25 while the node is being assigned with the address of 10.x.x.x/31. The code of Juju wasn't smart enough to realize the address' subnet on the node is a subset of the provider's subset hence was filtering it out.
We made a change of the code that is performing this comparison, now it explicitly checks if the address is in the subset of the provider's subnet and it all works.

**Comment by deitch** [comment]
Good to hear. I think we still should follow your recommendations, though. Good practice.

**Comment by displague** [comment]
I believe the initial issue reported here was addressed by #185 

https://github.com/equinix/cloud-provider-equinix-metal/blob/b5695ddaebffa3a5b12f4a61461b6325a51a4423/metal/devices.go#L58-L60

The provider id is the source of truth, falling back to other means.

**Comment by flokli** [comment]
I can't validate this anymore, as I don't have machines running in EQXM with that setup anymore.

Let's close this, if someone realizes this is still an issue it can be reopened.
