### ISSUE TITLE
MetalLB pods can not be read to detect MetalLB version

### ISSUE THREAD

**Issue by displague** [equinix/cloud-provider-equinix-metal#385]
Detecting MetalLB version by pod image is problematic. MetalLB pods can not be read to detect MetalLB version without proper RBAC. Pod image detection is tricky because namespaces, resource types, an resource names are all under the user's control.

Recommended approach is to have the user specify metallb version as a command line arg, environment variable, or configmap setting.

**Comment by Lirt** [comment]
Hi, I'm just testing latest commit of main branch (660ca1e102ee389ffd240d28c20954303a0ca01f)

I see different issue.

I configured `METAL_LOAD_BALANCER: "metallb:///kube-system"` (metallb is running in `kube-system`) according to docs.
```markdown
To enable it, set the configuration METAL_LOAD_BALANCER or config loadbalancer to:

metallb:///<configMapNamespace>

For example:

    metallb:///metallb-system - enable MetalLB management and update configuration in the namespace metallb-system (default)
    metallb:///foonamespace - enable MetalLB management and update configuration in the namespace metallb-system
    metallb:/// - enable MetalLB management and update configuration in the default namespace metallb-system
```

In the function `NewLB()` there is a splitting functionality. The value of `config` when function is started is `/kube-system`. First `/` is removed - value of `config` is `kube-system`. Then `cmparts` does basically nothing - so length of `cmparts` is 1. This way the `if len(cmparts) >= 2` is lower than 2 and namespace/configmapname is not populated.

Here is screenshot from debug session in VSCode:
![Screenshot from 2023-03-07 09-56-21](https://user-images.githubusercontent.com/11079428/223377579-b7a70697-460e-45d9-a7b0-1e6be415fac5.png)

Then since the `namespace` of MetalLB is wrong the code can't compare current/supported versions and doesn't use CRDs.

**Comment by ocobleseqx** [comment]
First approach I tried before adding that function was:

`metallb:///foonamespace/myconfig?version=x.y.z
`

It also fits with `metallb:///foonamespace/?version=x.y.z` or `metallb:///?version=x.y.z` or not setting any version to use latest.

I turned that option down to prevent users who want to upgrade cpem but keep an older version of metallb now needing to specify it, but it shouldn't be a big problem.

The code in metal/loadbalancers.go should be something like:

```
u, err := url.Parse(l.implementorConfig)
	if err != nil {
		return nil, fmt.Errorf("invalid config: %w", err)
	}
lbconfig := u.Path
extralbconfig, _ := url.ParseQuery(u.RawQuery)

...

case "metallb":
  klog.Info("loadbalancer implementation enabled: metallb")
  impl = metallb.NewLB(k8sclient, lbconfig, extralbconfig)  
```

And in the metal/loadbalancers/metallb/metallb.go :

```
func NewLB(k8sclient kubernetes.Interface, config string, extraconfig map[string]string) *LB {
  version := "9.9.9" // latest
  v, ok := extraconfig["version"]
  if ok {
    version = v
  }
```
