### ISSUE TITLE
EIP Facility Annotation ignored

### ISSUE THREAD

**Issue by TimJones** [equinix/cloud-provider-equinix-metal#409]
According to the docs, there is a (configurable) annotation for Service resources to select the facility from which an EIP can be associated, which by default is `metal.equinix.com/eip-facility`.

From my testing, this annotation is ignored, while the metro-based `metal.equinix.com/eip-metro` annotation works as expected.

**Comment by ctreatma** [comment]
One thing to note is that [the facilities concept is being deprecated this year](https://feedback.equinixmetal.com/changelog/bye-facilities-hello-again-metros), so while we should fix support for the annotation in order to match the docs, we highly recommend that any customers currently using the facility-based annotation adopt the metro-based annotation instead.
